### ISSUE TITLE
concept list underlying the study

### ISSUE THREAD

**Issue by LinguList** [lexibank/lieberherrkhobwa#11]
> Since our objective was to determine whether the languages purported to be Kho-Bwa languages derived from a common ancestor language, we started from the Leipzig-Jakarta 100 items list (Haspelmath and Tadmor 2009)

This is a quote (page 30) from the original paper. It explains the whereabouts of the wordlist. The authors are aware of the concepticon, as they quote the sentence before.

**Comment by LinguList** [comment]
This information should be included when adding the concept list to concepticon.

**Comment by tresoldi** [comment]
This is postponed until their paper is published (or, at least, accepted).

**Comment by LinguList** [comment]
I mean, I have the paper here.

**Comment by SimonGreenhill** [comment]
Looks published to me: https://escholarship.org/uc/item/4t27h5fg

**Comment by LinguList** [comment]
Yes, totally. @tresoldi, is the list in concepticon now?

**Comment by LinguList** [comment]
The list is in concepticon now, so we should update lexibank code. @chrzyki or @tresoldi who can look into that?

**Comment by chrzyki** [comment]
Will take care of this.

**Comment by chrzyki** [comment]
Done in #16
