### ISSUE TITLE
khobwa-data officially online

### ISSUE THREAD

**Issue by LinguList** [lexibank/lieberherrkhobwa#12]
https://github.com/metroxylon/subgrouping-kho-bwa/blob/master/data/dataset_khobwa.csv

Did any of you see this before? I mean, the data is slightly re-ordered, making processing easier.

**Comment by LinguList** [comment]
I think, while we can make a 0.1.0 or so, we should use this csv data above later. It is much more consistent and also illustrates the benefits of sharing data on github, as they do nicely in their repository.

**Comment by xrotwang** [comment]
We should copy [release 1.0.0](https://github.com/metroxylon/subgrouping-kho-bwa/releases) to `raw/` and work from there.

**Comment by LinguList** [comment]
Yes. What I think, happened, is that they decided to submit not only csv, but some excel, then they may have been asked to change that. So the data that actually works is the github thing, and the confusion we had with missing entries was due to the excel conversions, as they'd have noticed this in their csv-file as well, I guess.
