### ISSUE TITLE
Steps for finalizing the dataset

### ISSUE THREAD

**Issue by LinguList** [lexibank/lieberherrkhobwa#19]
- [x] submit the orthography profile to orthograpy (see closed issue)
- [x] add the notes.md, describing quickly the dataset
- [x] assign contributors.md to reflect all involved
- [x] merge PR on pylexibank, where the metadata now allows for a patron
- [x] add patron for this dataset (e.g., I suggest, @tresoldi) to metadata (once decided this discussion)
- [ ] make a version and publish with zenodo

**Comment by SimonGreenhill** [comment]
where are we on these things?

**Comment by LinguList** [comment]
Yes, @chrzyki and @tresoldi, can we please leave this to the two of you? Please check specifically the concepticon mapping and make sure it is in a good state, as this will also be submitted for the data managment paper.

**Comment by chrzyki** [comment]
Okay, will coordinate with @tresoldi.

**Comment by chrzyki** [comment]
Anything in particular you'd like to see in the `NOTES.md`, @LinguList?

**Comment by chrzyki** [comment]
Most things are done now but I suggest we wait for a Concepticon release (and a rebuild of the dataset) until pushing it to Zenodo.

**Comment by LinguList** [comment]
I think the content of the NOTES.md is up to you and @tresoldi, to make a first proposal, as this is underlying the MIT press paper, and you were the ones in charge for this ;) I'll comment, once I see the notes.

**Comment by chrzyki** [comment]
Sounds good. I'll prepare something.

**Comment by chrzyki** [comment]
Done except for the release which will follow.
