### ISSUE TITLE
Add custom commandline code to transform the data to nexus and the like

### ISSUE THREAD

**Issue by LinguList** [lexibank/lieberherrkhobwa#22]
We can now add the code, as you can see from [chenhmongmien](https://github.com/lexibank/chenhmongmien). I suggest we do the same for the MIT paper.

**Comment by chrzyki** [comment]
Pretty bare bones: https://github.com/lexibank/lieberherrkhobwa/commit/8cd82a44638fe70c787063a68236409385b8aac9

Anything else you'd like to see added?

**Comment by chrzyki** [comment]
Done
