### ISSUE TITLE
thorough manual check of the data 

### ISSUE THREAD

**Issue by LinguList** [lexibank/lieberherrkhobwa#24]
I would strongly suggest to check the data manually before submitting a final version for the paper. This includes also things like phoneme inventories and the like, plus a run with the most recent pylexibank code plus most recent clts. A pre-release can also be done, this will give us the DOI, and we can then use the `latestdoi` from Zenodo in the paper.

**Comment by chrzyki** [comment]
I've updated and checked as much as I can. Are you fine with a (pre-)release?

**Comment by MuffinLinwist** [comment]
Can I ask what's the status on this? Seems to me that the ortho-profile could be improved a little further.

**Comment by LinguList** [comment]
I will try and check the profile. But not today.

**Comment by chrzyki** [comment]
Sorry and thanks for the reminder. I can also help.

**Comment by LinguList** [comment]
I just checked the data running EDICTOR 3 with cognate sets and correspondence patterns. The data look okay to me. They are not super good (some morphemes are not clearly segmented) but this is okay given that we do not explicitly work with the dataset now and that the data was not compiled for this purpose.

**Comment by MuffinLinwist** [comment]
Thanks, @LinguList and @chrzyki. I'll close this issue for now then.

**Comment by LinguList** [comment]
yes, thanks!
